apiVersion: v1
kind: Secret
metadata:
  name: argo-app-go-server
  namespace: go-server-ns
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/natanbs/
  password: natanbs
  username: 'Bamba@48'
